---
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Validate gradle wrapper checksum
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20
          cache: gradle

      - name: Build and test
        # Debug build only since release builds require a signing key
        run: ./gradlew --no-daemon build zipDebug -x assembleRelease

  build-tool:
    name: Build custota-tool
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd custota-tool
          cargo clippy
          cargo fmt -- --check
          cargo build --verbose
